use rustrade_execution::error::AccountStreamInitError;
use serde::{Deserialize, Serialize};
use thiserror::Error;

/// Represents all errors generated by the execution link.
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Error)]
pub enum ExecutionError {
    /// Indicates an invalid execution manager configuration.
    #[error("ExecutionManager config invalid: {0}")]
    Config(String),

    /// The first attempt to initialise the exchange account stream, its snapshot and its updates,
    /// failed. Later failed attempts arrive in-band as
    /// [`AccountEventKind::ReinitFailed`](rustrade_execution::AccountEventKind::ReinitFailed).
    #[error("account stream initialisation failed: {0}")]
    AccountStreamInit(#[from] AccountStreamInitError),
}
